---
# ROS 2 configuration variables
ros_distro: jazzy
source_install: false # Set to true for source installation
clang_version: 20
ci_mode: false # Set to true for CI environment

# ROS user configuration
setup_user: false # Do not setup user by default, used by docker only
ros_user_setup_username: rosdev
ros_user_setup_uid: 1001
ros_user_setup_gid: 1001

# Xpra configuration
install_xpra: false # Set to true to install Xpra + VirtualGL for GUI rendering
